POST http://127.0.0.1:8000/api/v1/jwt/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMDk3Njc5LCJpYXQiOjE3MzAwMTEyNzksImp0aSI6IjgzZDVhZGRjMzdkMjRhN2FiOTQ0MDRhNzgxZmM4NTM4IiwidXNlcl9pZCI6MX0.0IOrC2pP65LbFxp0aDj9EjbVdpbpMPZlAgxOvtcWdsg
Content-Type: application/json

{
    "username": "qwe",
    "password": "qwe123"
}

###

GET http://127.0.0.1:8000/api/v1/posts/?limit=2&offset=4

###

POST http://127.0.0.1:8000/api/v1/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjY2NDQyLCJpYXQiOjE3MzAxODAwNDIsImp0aSI6IjMyOTFiZjcxYTBkMTQwMjM5OTI0ZGM3YWNhOGM1YjUyIiwidXNlcl9pZCI6MX0.Q7oBPZ__n8NkyPIBlS9Uw9EpdGL5Ii0XT0AJBcegWf4
Content-Type: application/json

{
"text": "strinasdfgasfdasd"
}

###

GET http://127.0.0.1:8000/api/v1/posts/2/comments/

Content-Type: application/json

{
    "text": "ХАХА"
}

###

DELETE http://127.0.0.1:8000/api/v1/posts/13/



###

GET http://127.0.0.1:8000/api/v1/posts/13/comments/
Content-Type: application/json

{
    "text": "ХАХА"
}
